"""Drug examples for discussion with a veterinarian, conditional on confirmation."""
DRUGS = {
 'Dermatitis':'Không có một thuốc chung cho mọi viêm da. Nếu xác nhận nhiễm khuẩn, nấm hoặc ký sinh trùng, thú y chọn thuốc theo tác nhân. Không tự bôi corticoid lên tổn thương chưa rõ nguyên nhân hoặc dùng thuốc giảm đau của người cho chó.',
 'Fungal_infections':'Sau khi xác nhận loại nấm, thú y có thể cân nhắc thuốc tại chỗ chứa miconazole hoặc thuốc toàn thân như itraconazole trong trường hợp phù hợp. Cần đánh giá tuổi, thai kỳ, chức năng gan và thuốc dùng kèm; chó phải được ngăn liếm thuốc bôi. Không dùng kết quả ảnh để tự chọn thuốc.',
 'ringworm':'Nếu xác nhận nấm dermatophyte, các lựa chọn thú y có thể cân nhắc gồm điều trị tại chỗ chứa miconazole kết hợp vệ sinh môi trường, và itraconazole toàn thân khi cần. Thời gian điều trị dựa vào đáp ứng và xét nghiệm theo dõi, không chỉ lúc lông mọc lại; cần xem xét chức năng gan và chống chỉ định.',
 'Hypersensitivity':'Thú y có thể cân nhắc thuốc kiểm soát ngứa như oclacitinib hoặc lokivetmab khi phù hợp, đồng thời xử lý dị nguyên và nhiễm trùng đi kèm. Các thuốc này không chữa mọi nguyên nhân gây ngứa, có giới hạn tuổi/chống chỉ định và không thay thế kiểm soát bọ chét.',
 'demodicosis':'Sau khi xác nhận Demodex, thú y có thể lựa chọn thuốc nhóm isoxazoline như fluralaner hoặc afoxolaner tùy sản phẩm được phép dùng và tình trạng chó. Cần báo tiền sử co giật/bệnh thần kinh, tuổi, cân nặng và thai kỳ. Không tự dùng ivermectin vì có nguy cơ độc tính ở chó nhạy cảm.',
 'foot_and_mouth':'Không có thuốc đặc hiệu để tự chữa virus lở mồm long móng. Thú y chỉ định chăm sóc hỗ trợ, giảm đau và điều trị nhiễm khuẩn thứ phát nếu có. Kháng sinh không diệt virus; vaccine dùng phòng bệnh, không phải thuốc chữa con đang bệnh.',
 'lumpy_skin':'Không có thuốc đặc hiệu để tự chữa virus viêm da nổi cục. Thú y cân nhắc chăm sóc hỗ trợ, giảm đau và kháng sinh chỉ khi có nhiễm khuẩn thứ phát. Không tự tiêm phối hợp nhiều thuốc; vaccine là biện pháp phòng bệnh theo chương trình kiểm soát dịch.',
 'mastitis':'Thuốc kháng sinh tại vú hoặc toàn thân chỉ được chọn theo tác nhân và mức độ viêm vú; không thể chọn từ ảnh bầu vú. Ca nặng có thể cần truyền dịch và thuốc chống viêm do thú y thực hiện. Không tự bơm thuốc vào núm vú; bắt buộc tuân thủ thời gian ngừng sử dụng sữa và thịt theo sản phẩm.',
 'Coccidiosis':'Nếu xác nhận cầu trùng, thú y có thể cân nhắc amprolium hoặc toltrazuril tùy loài/nhóm tuổi, chương trình phòng bệnh và sản phẩm được phép sử dụng. Không tự phối nhiều thuốc cầu trùng. Với gà đẻ, phải kiểm tra sản phẩm có được phép dùng khi trứng làm thực phẩm hay không và thời gian ngừng thuốc.',
 'New Castle Disease':'Không có kháng sinh chữa virus Newcastle. Thuốc hỗ trợ hoặc xử lý bội nhiễm chỉ dùng theo thú y và không thay thế kiểm soát ổ dịch. Không tự dùng vaccine như thuốc chữa gà đang mắc bệnh.',
 'Salmonella':'Không chọn kháng sinh chỉ từ ảnh phân. Nếu thú y chỉ định điều trị, lựa chọn phải dựa vào xét nghiệm, độ nhạy kháng sinh và quy định với gia cầm thực phẩm. Điều trị không bảo đảm loại bỏ mang trùng; cần kiểm soát đàn, nguồn giống và an toàn thực phẩm.',
 'Erysipelas':'Khi thú y xác nhận hoặc có đủ chỉ định lâm sàng cho bệnh đóng dấu lợn, penicillin là một lựa chọn kháng sinh thường được cân nhắc. Thuốc, đường dùng, thời gian điều trị và ngừng thuốc phải do thú y xác định theo sản phẩm, cân nặng và mức độ bệnh. Không tự tiêm khi chỉ có ảnh da đỏ tím vì có thể là bệnh khác.',
 'Greasy_Pig_Disease':'Thú y có thể cân nhắc kháng sinh như lincomycin hoặc penicillin nếu tác nhân còn nhạy; Staphylococcus hyicus có thể kháng thuốc nên không có lựa chọn chắc chắn chỉ từ ảnh. Cần đánh giá mất nước, lấy mẫu khi phù hợp, chăm sóc da và tuân thủ thời gian ngừng thuốc. Không tự dùng kháng sinh dự phòng cho cả đàn.',
 'Sarcoptic_Mange':'Nếu xác nhận ghẻ Sarcoptes ở lợn, thú y có thể cân nhắc ivermectin hoặc doramectin theo sản phẩm được phép dùng. Lịch nhắc điều trị và xử lý đàn tiếp xúc phải theo kế hoạch; kiểm tra thai kỳ, tuổi, cân nặng và thời gian ngừng thuốc trước xuất bán.',
 'unknown':'Chưa nhận diện được bệnh thuộc lớp hỗ trợ nên không đưa ra thuốc điều trị. Cần khám trực tiếp nếu con vật có triệu chứng; không thử các thuốc của những bệnh xuất hiện ở kết quả khác.',
 'healthy':'Không có chỉ định dùng thuốc từ nhãn đối chứng bình thường. Nếu con vật vẫn có triệu chứng, cần khám; không tự dùng kháng sinh hoặc thuốc phòng chỉ vì đã phân tích ảnh.',
 'oral_signs_unverified':'Không chọn thuốc từ ảnh miệng/nước dãi. Nếu nghi dại, không có cách tự điều trị tại nhà; tránh tiếp xúc và báo thú y. Nếu nghi ngộ độc hoặc chó khó nuốt/co giật, không ép uống hay tự gây nôn. Người bị phơi nhiễm cần cơ sở y tế đánh giá vaccine/huyết thanh dự phòng, không dùng thuốc thú y cho người.'
}

def medication(label):
    return DRUGS['healthy' if label.lower()=='healthy' else label]
